name: pbmc-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - scanpy
  - anndata
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - h5py
  - pybedtools
  - bedtools
  - pip